In [1]:
import numpy as np
train_inputs = np.array([0,1,2,3,4])
train_outputs = np.array([0, 6, 12, 18,24])
for i in range(3):
    Weight=int(input("Enter the Value of Weight"))
    pred_output=train_inputs*Weight
    error=pred_output-train_outputs
    print("Predicted Output: ",pred_output)
    print("Desired Output: ",train_outputs)
    print("Errors",error)

Enter the Value of Weight 13


Predicted Output:  [ 0 13 26 39 52]
Desired Output:  [ 0  6 12 18 24]
Errors [ 0  7 14 21 28]


Enter the Value of Weight 31


Predicted Output:  [  0  31  62  93 124]
Desired Output:  [ 0  6 12 18 24]
Errors [  0  25  50  75 100]


Enter the Value of Weight 29


Predicted Output:  [  0  29  58  87 116]
Desired Output:  [ 0  6 12 18 24]
Errors [ 0 23 46 69 92]


In [3]:
import numpy as np
D=np.array([[1,2,3],
          [1,0,2],
          [0,1,4],
          [2,1,4]])
np.random.seed(1)
w=np.random.random((3,1))
print("Weight Matrix: ")
print(w)
for i in range(1):
    il=D
    op=np.dot(il,w)
    ol=1/(1+np.exp(-op))
print("Input: ")
print(D)
print("Predicted output: ")
print(ol)

Weight Matrix: 
[[4.17022005e-01]
 [7.20324493e-01]
 [1.14374817e-04]]
Input: 
[[1 2 3]
 [1 0 2]
 [0 1 4]
 [2 1 4]]
Predicted output: 
[[0.86506531]
 [0.60282519]
 [0.67277919]
 [0.82560966]]


In [5]:
import numpy as np
D=np.array([[1,2,3],
          [1,0,2],
          [0,1,4],
          [2,1,4]])
np.random.seed(1)
w=np.random.random((3,2))
print("Weight Matrix: ")
print(w)
for i in range(1):
    il=D
    op=np.dot(il,w)
    ol=1/(1+np.exp(-op))
print("Input: ")
print(D)
print("Predicted output: ")
print(ol)

Weight Matrix: 
[[4.17022005e-01 7.20324493e-01]
 [1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02]]
Input: 
[[1 2 3]
 [1 0 2]
 [0 1 4]
 [2 1 4]]
Predicted output: 
[[0.70214192 0.83229848]
 [0.6705191  0.71197626]
 [0.64270819 0.66188079]
 [0.80552364 0.8920964 ]]


In [7]:
import numpy as np
D=np.array([[1,2,3],
          [1,0,2],
          [0,1,4],
          [2,1,4]])
np.random.seed(1)
w=np.random.random((3,4))
print("Weight Matrix: ")
print(w)
print("V weight matrix")
v=np.random.random((4,2))
for i in range(1):
    il=D
    hp=np.dot(il,w)
    hl=1/(1+np.exp(-hp))
    op=np.dot(hl,v)
    ol=1/(1+np.exp(-op))
print("Input: ")
print(D)
print("Predicted output: ")
print(ol)

Weight Matrix: 
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01]
 [3.96767474e-01 5.38816734e-01 4.19194514e-01 6.85219500e-01]]
V weight matrix
Input: 
[[1 2 3]
 [1 0 2]
 [0 1 4]
 [2 1 4]]
Predicted output: 
[[0.66512221 0.88502169]
 [0.64349012 0.85918454]
 [0.66686308 0.88347877]
 [0.67146728 0.89535013]]
